#!/usr/bin/env bash
# Regenerate the two committed artifacts that carry the database schema into the
# other subsystems, both derived from the same live local Supabase instance:
#
#   app/src/generated/database.ts         TypeScript row/insert/update types,
#                                         produced by `supabase gen types`, that
#                                         `createClient<Database>` uses to type
#                                         every `.from(...).select(...)` call.
#   integration/tests/fixtures/public_schema.json
#                                         the same schema read back out of
#                                         information_schema, for the Python
#                                         contract test that checks the row
#                                         dicts the pipeline writes. Generated
#                                         TypeScript does nothing for pipeline/.
#
# Both are generated. Never hand-edit either one - edit a migration and re-run
# this script. `.github/workflows/tests.yml` re-runs it against the instance the
# app job already starts and fails on any diff, so a migration that lands
# without a regeneration reddens the build instead of drifting quietly.
#
# Needs Docker: `supabase gen types` runs the postgres-meta image in a
# container, and `supabase start` boots the stack. There is no Docker-free path.
set -euo pipefail

if ! command -v psql >/dev/null 2>&1; then
  echo "gen-db-types: psql is required to dump the schema fixture" >&2
  exit 1
fi

repo_root="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
cd "$repo_root"

types_out="app/src/generated/database.ts"
fixture_out="integration/tests/fixtures/public_schema.json"

# `supabase start` applies the migrations itself, but a stack that is already up
# may predate the ones in the working tree. Reusing it without catching it up
# would generate both artifacts from a schema older than
# supabase/migrations/*.sql, contradicting the header this script writes.
started_stack=0
if ! supabase status >/dev/null 2>&1; then
  echo "gen-db-types: starting local Supabase" >&2
  supabase start
  started_stack=1
else
  echo "gen-db-types: reusing running local Supabase, applying pending migrations" >&2
  supabase migration up --local
fi
cleanup() {
  if [ "$started_stack" = 1 ]; then
    supabase stop >/dev/null
  fi
}
trap cleanup EXIT

# --schema public is explicit rather than inherited from config.toml's
# api.schemas (which also lists graphql_public): the app queries nothing outside
# public, and pinning it here keeps the output stable if that config changes.
generated="$(supabase gen types typescript --local --schema public)"

mkdir -p "$(dirname "$types_out")"
{
  echo "// Code generated by scripts/gen-db-types.sh (npm run gen:types). DO NOT EDIT."
  echo "//"
  echo "// Source of truth: supabase/migrations/*.sql, read back out of a live local"
  echo "// Supabase instance by \`supabase gen types typescript --local --schema public\`."
  echo "// Regenerate after any migration; CI fails on drift."
  echo
  printf '%s\n' "$generated"
} > "$types_out"

eval "$(supabase status -o env | sed -n 's/^DB_URL=/db_url=/p')"

mkdir -p "$(dirname "$fixture_out")"
psql "$db_url" --no-psqlrc --quiet --tuples-only --no-align \
  --file=/dev/stdin > "$fixture_out" <<'SQL'
select jsonb_pretty(jsonb_build_object(
  'generated_by', 'scripts/gen-db-types.sh',
  'source', 'information_schema.columns, schema public, base tables only',
  'tables', coalesce(jsonb_object_agg(table_name, columns), '{}'::jsonb)
))
from (
  select
    c.table_name,
    jsonb_object_agg(
      c.column_name,
      jsonb_build_object(
        'data_type', c.data_type,
        'is_nullable', c.is_nullable = 'YES',
        'has_default', c.column_default is not null
      )
      order by c.column_name
    ) as columns
  from information_schema.columns c
  join information_schema.tables t
    on t.table_schema = c.table_schema
   and t.table_name = c.table_name
  where c.table_schema = 'public'
    and t.table_type = 'BASE TABLE'
  group by c.table_name
) per_table;
SQL

echo "gen-db-types: wrote $types_out and $fixture_out" >&2
